2018-06-29 11:14:13,438 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2018-06-29 11:14:32,678 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-06-29 11:14:33,058 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/commons.js
2018-06-29 11:14:33,499 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/commons.js
2018-06-29 11:14:58,797 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-06-29 11:48:11,403 [HttpRunnerManager:151] [operation:add_case_data] [INFO]- 的用例添加成功: {'test': {'request': {'method': 'POST', 'url': ''}, 'name': '的'}}
2018-06-29 11:48:48,076 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:34:18,047 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/css/css-index.css
2018-07-02 13:34:18,057 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/logo.png
2018-07-02 13:34:18,268 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:18,270 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:18,276 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:18,278 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:18,296 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/bg.jpg
2018-07-02 13:34:18,299 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/loading.GIF
2018-07-02 13:34:18,352 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:18,364 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:18,370 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:18,383 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:18,578 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/favicon.ico
2018-07-02 13:34:21,442 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/css/css-index.css
2018-07-02 13:34:21,445 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:21,449 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/logo.png
2018-07-02 13:34:21,484 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:21,487 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:21,492 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:21,508 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:21,516 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/bg.jpg
2018-07-02 13:34:21,519 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/loading.GIF
2018-07-02 13:34:21,531 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:21,540 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:21,545 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:22,424 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/css/css-index.css
2018-07-02 13:34:22,426 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/logo.png
2018-07-02 13:34:22,429 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:22,465 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:22,466 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:22,468 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:22,480 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:22,483 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/bg.jpg
2018-07-02 13:34:22,490 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/loading.GIF
2018-07-02 13:34:22,498 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:22,506 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:22,509 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:35:30,488 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:48:28,352 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:53:41,984 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/test_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:/HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:/HttpRunnerManager\ApiManager\views.py", line 379, in test_list
    filter_query = set_filter_session(request)
  File "D:/HttpRunnerManager\ApiManager\utils\common.py", line 439, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 13:53:49,147 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/test_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:/HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:/HttpRunnerManager\ApiManager\views.py", line 379, in test_list
    filter_query = set_filter_session(request)
  File "D:/HttpRunnerManager\ApiManager\utils\common.py", line 439, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 13:54:04,117 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 13:54:07,459 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:57:09,661 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 13:57:11,824 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:04:39,039 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:04:44,830 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:04:54,650 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/test_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 379, in test_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 432, in set_filter_session
    request.session['module'] = ModuleInfo.objects.get(id=request.POST.get('module')).module_name
  File "E:\Python35\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 394, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 68, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\Python35\lib\site-packages\django\db\models\fields\__init__.py", line 947, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
2018-07-02 14:06:02,565 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/config_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 413, in config_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 432, in set_filter_session
    request.session['module'] = ModuleInfo.objects.get(id=request.POST.get('module')).module_name
  File "E:\Python35\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 394, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 68, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\Python35\lib\site-packages\django\db\models\fields\__init__.py", line 947, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
2018-07-02 14:24:14,328 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:24:16,921 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:27:17,963 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 323, in project_list
    return render_to_response('project_list.html', manage_info)
  File "E:\Python35\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\Python35\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Python35\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Python35\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 176: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2018-07-02 14:27:44,949 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 323, in project_list
    return render_to_response('project_list.html', manage_info)
  File "E:\Python35\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\Python35\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Python35\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Python35\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 176: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2018-07-02 14:27:47,983 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 323, in project_list
    return render_to_response('project_list.html', manage_info)
  File "E:\Python35\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\Python35\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Python35\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Python35\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 176: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2018-07-02 14:28:16,257 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:28:18,192 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:37:16,138 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 311, in project_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 442, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 14:37:20,563 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 311, in project_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 442, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 14:37:24,899 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:37:26,773 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:37:30,837 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/add_case/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 170, in add_case
    msg = case_info_logic(**testcase_info)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 210, in case_info_logic
    test = kwargs.pop('test')
KeyError: 'test'
2018-07-02 14:37:33,775 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/add_case/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 170, in add_case
    msg = case_info_logic(**testcase_info)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 210, in case_info_logic
    test = kwargs.pop('test')
KeyError: 'test'
2018-07-02 14:39:25,603 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:39:27,918 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:43:42,829 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:43:44,932 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:47:52,728 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:47:54,981 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:55:50,890 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:55:53,036 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:57:17,859 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/module_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 345, in module_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 433, in set_filter_session
    request.session['module'] = ModuleInfo.objects.get(id=request.POST.get('module')).module_name
  File "E:\Python35\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 394, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 68, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\Python35\lib\site-packages\django\db\models\fields\__init__.py", line 947, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '用例_quant_login_out(登入登出)'
2018-07-02 14:59:50,449 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:59:52,333 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2019-06-12 10:33:04,818 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-06-12 10:33:48,925 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-06-12 10:33:56,318 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-06-12 10:37:55,770 [HttpRunnerManager:35] [operation:add_register_data] [INFO]- 新增用户：ApiManager.UserInfo.objects
2019-06-12 10:38:03,935 [HttpRunnerManager:55] [views:login] [INFO]- alita 登录成功
2019-06-12 11:16:22,681 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-06-12 11:16:49,264 [django.request:93] [base:get_response] [WARNING]- Not Found: /api
2019-06-12 11:17:13,817 [HttpRunnerManager:60] [views:login] [INFO]- alita 登录失败, 请检查用户名或者密码
2019-06-12 11:17:21,357 [HttpRunnerManager:60] [views:login] [INFO]- alita 登录失败, 请检查用户名或者密码
2019-06-12 11:17:49,864 [HttpRunnerManager:60] [views:login] [INFO]- alita 登录失败, 请检查用户名或者密码
2019-06-12 11:18:02,177 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:18:35,535 [HttpRunnerManager:60] [views:login] [INFO]- alita 登录失败, 请检查用户名或者密码
2019-06-12 11:18:36,415 [HttpRunnerManager:60] [views:login] [INFO]-  登录失败, 请检查用户名或者密码
2019-06-12 11:18:36,781 [HttpRunnerManager:60] [views:login] [INFO]-  登录失败, 请检查用户名或者密码
2019-06-12 11:18:36,970 [HttpRunnerManager:60] [views:login] [INFO]-  登录失败, 请检查用户名或者密码
2019-06-12 11:18:37,146 [HttpRunnerManager:60] [views:login] [INFO]-  登录失败, 请检查用户名或者密码
2019-06-12 11:18:52,490 [HttpRunnerManager:29] [operation:add_register_data] [DEBUG]- alita 已被其他用户注册
2019-06-12 11:19:11,129 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:19:17,599 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:19:18,479 [HttpRunnerManager:60] [views:login] [INFO]-  登录失败, 请检查用户名或者密码
2019-06-12 11:19:18,677 [HttpRunnerManager:60] [views:login] [INFO]-  登录失败, 请检查用户名或者密码
2019-06-12 11:19:18,856 [HttpRunnerManager:60] [views:login] [INFO]-  登录失败, 请检查用户名或者密码
2019-06-12 11:19:19,013 [HttpRunnerManager:60] [views:login] [INFO]-  登录失败, 请检查用户名或者密码
2019-06-12 11:20:59,690 [HttpRunnerManager:89] [views:log_out] [INFO]- alita退出
2019-06-12 11:21:01,699 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:21:03,036 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:21:04,587 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:21:04,867 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:21:05,085 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:21:05,320 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:21:05,492 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:21:05,730 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:21:08,468 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:21:15,732 [HttpRunnerManager:60] [views:login] [INFO]- alita 登录失败, 请检查用户名或者密码
2019-06-12 11:21:16,670 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:21:21,197 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:21:35,169 [HttpRunnerManager:60] [views:login] [INFO]- alita 登录失败, 请检查用户名或者密码
2019-06-12 11:21:36,085 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:22:05,210 [HttpRunnerManager:60] [views:login] [INFO]- alita 登录失败, 请检查用户名或者密码
2019-06-12 11:22:13,387 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-12 11:22:14,119 [HttpRunnerManager:60] [views:login] [INFO]-  登录失败, 请检查用户名或者密码
2019-06-12 11:23:11,078 [HttpRunnerManager:60] [views:login] [INFO]-  登录失败, 请检查用户名或者密码
2019-06-12 11:23:17,210 [HttpRunnerManager:55] [views:login] [INFO]- alita 登录成功
2019-06-12 11:27:13,278 [HttpRunnerManager:62] [operation:add_project_data] [INFO]- 项目添加成功：{'project_name': 'api_test', 'responsible_name': 'test', 'test_user': 'test_wang', 'dev_user': 'test', 'publish_app': 'test', 'simple_desc': '', 'other_desc': ''}
2019-06-12 11:28:06,538 [HttpRunnerManager:110] [operation:add_module_data] [INFO]- 模块添加成功：{'module_name': 'api_demo', 'test_user': 'test_wang', 'simple_desc': '', 'other_desc': '', 'belong_project': <ProjectInfo: ProjectInfo object (1)>}
2019-06-12 11:29:27,513 [HttpRunnerManager:154] [operation:add_case_data] [INFO]- api_01用例添加成功: {'test': {'request': {'url': 'http://httpbin.org/get', 'method': 'GET'}, 'name': 'api_01'}}
2019-06-12 11:56:53,917 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- api_test_get用例更新成功: {'test': {'request': {'url': '/get', 'method': 'GET'}, 'name': 'api_test_get'}}
2019-06-12 17:25:24,505 [HttpRunnerManager:76] [operation:add_project_data] [INFO]- 项目更新成功：{'project_name': 'api_test', 'responsible_name': 'test', 'test_user': 'test_wang', 'dev_user': 'test', 'publish_app': 'test', 'simple_desc': '', 'other_desc': ''}
2019-06-13 08:47:52,615 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-06-13 08:48:21,618 [HttpRunnerManager:60] [views:login] [INFO]- alita 登录失败, 请检查用户名或者密码
2019-06-13 08:48:27,940 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-13 08:48:29,725 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-13 08:48:30,387 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-13 08:48:30,557 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-13 08:48:30,736 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-13 08:48:30,948 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-13 08:48:31,140 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-13 08:48:38,709 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-13 08:48:39,313 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-13 08:48:40,524 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-13 08:48:45,348 [HttpRunnerManager:60] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-06-13 08:49:43,658 [HttpRunnerManager:55] [views:login] [INFO]- alita 登录成功
2019-06-13 08:55:36,816 [HttpRunnerManager:62] [operation:add_project_data] [INFO]- 项目添加成功：{'project_name': '小程序', 'responsible_name': 'test_wang', 'test_user': 'test_wang', 'dev_user': 'test', 'publish_app': 'test', 'simple_desc': '小程序', 'other_desc': '小程序'}
2019-06-13 08:56:32,975 [HttpRunnerManager:110] [operation:add_module_data] [INFO]- 模块添加成功：{'module_name': 'BindCompany', 'test_user': 'test_wang', 'simple_desc': '', 'other_desc': '', 'belong_project': <ProjectInfo: ProjectInfo object (2)>}
2019-06-13 08:57:26,978 [HttpRunnerManager:154] [operation:add_case_data] [INFO]- login用例添加成功: {'test': {'request': {'url': '/commonapi/', 'method': 'GET'}, 'name': 'login'}}
2019-06-13 08:59:26,588 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- login用例更新成功: {'test': {'request': {'url': '/commonapi/', 'method': 'POST'}, 'name': 'login'}}
2019-06-13 09:01:08,530 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- login用例更新成功: {'test': {'request': {'url': '/commonapi/', 'method': 'POST', 'data': {'action': 'Indexs.LoginByPwd', 'time': '0', 'phone': '17706120671', 'pwd': 'e10adc3949ba59abbe56e057f20f883e', 'key': '505'}}, 'name': 'login'}}
2019-06-13 09:02:02,984 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- login用例更新成功: {'test': {'request': {'url': '/commonapi/', 'method': 'POST', 'data': {'action': 'Indexs.LoginByPwd', 'time': '0', 'phone': '17706120671', 'pwd': 'e10adc3949ba59abbe56e057f20f883e', 'key': '505'}}, 'name': 'login', 'extract': [{'token': 'data.data.token'}]}}
2019-06-13 09:04:35,553 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- login用例更新成功: {'test': {'request': {'url': '/commonapi/', 'method': 'POST', 'data': {'action': 'Indexs.LoginByPwd', 'time': '0', 'phone': '17706120671', 'pwd': 'e10adc3949ba59abbe56e057f20f883e', 'key': '505'}}, 'name': 'login', 'extract': [{'token': 'content.data.data.token'}]}}
2019-06-13 09:10:32,801 [HttpRunnerManager:154] [operation:add_case_data] [INFO]- 正常绑定公司用例添加成功: {'test': {'request': {'url': '/b2bapi/', 'method': 'POST', 'json': {'action': 'Xiaochengxu.BindCompany', 'token': '${token}', 'company_id': '1463', 'status': '1'}}, 'name': '正常绑定公司'}}
2019-06-13 09:16:19,575 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 正常绑定公司用例更新成功: {'test': {'request': {'url': '/b2bapi/', 'method': 'POST', 'json': {'action': 'Xiaochengxu.BindCompany', 'token': '$token', 'company_id': '1463', 'status': '1'}}, 'name': '正常绑定公司'}}
2019-06-13 09:58:17,641 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- login用例更新成功: {'test': {'request': {'url': 'http://apicommontest.hongyantu.com/commonapi/', 'method': 'POST', 'data': {'action': 'Indexs.LoginByPwd', 'time': '0', 'phone': '17706120671', 'pwd': 'e10adc3949ba59abbe56e057f20f883e', 'key': '505'}}, 'name': 'login', 'extract': [{'token': 'content.data.data.token'}]}}
2019-06-13 10:01:15,277 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 正常绑定公司用例更新成功: {'test': {'request': {'url': '/b2bapi/', 'method': 'POST', 'data': {'action': 'Xiaochengxu.BindCompany', 'token': '$token', 'company_id': '1463', 'status': '1'}}, 'name': '正常绑定公司'}}
2019-06-13 10:05:31,579 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 正常绑定公司用例更新成功: {'test': {'request': {'url': '/b2bapi/', 'method': 'POST', 'data': {'action': 'Xiaochengxu.BindCompany', 'token': '${token}', 'company_id': '1463', 'status': '1'}}, 'name': '正常绑定公司'}}
2019-06-13 10:09:03,710 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 正常绑定公司用例更新成功: {'test': {'request': {'url': '/b2bapi/', 'method': 'POST', 'data': {'action': 'Xiaochengxu.BindCompany', 'token': '$token', 'company_id': '1463', 'status': '1'}}, 'name': '正常绑定公司'}}
2019-06-13 10:12:26,340 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 正常绑定公司用例更新成功: {'test': {'request': {'url': '/b2bapi/', 'method': 'POST', 'data': {'action': 'Xiaochengxu.BindCompany', 'token': '$token', 'company_id': '1463', 'status': '1'}}, 'name': '正常绑定公司'}}
2019-06-13 10:13:58,690 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 正常绑定公司用例更新成功: {'test': {'request': {'url': '/b2bapi/', 'method': 'POST', 'json': {'action': 'Xiaochengxu.BindCompany', 'token': '$token', 'company_id': '1463', 'status': '1'}}, 'name': '正常绑定公司'}}
2019-06-13 10:23:45,771 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- 正常绑定公司用例更新成功: {'test': {'request': {'url': '/b2bapi/', 'method': 'POST', 'json': {'action': 'Xiaochengxu.BindCompany', 'token': '$token', 'company_id': '1463', 'status': '1'}}, 'name': '正常绑定公司'}}
2019-06-13 10:27:43,515 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- login用例更新成功: {'test': {'request': {'url': 'http://apicommontest.hongyantu.com/commonapi/', 'method': 'POST', 'data': {'action': 'Indexs.LoginByPwd', 'time': '0', 'phone': '17706120671', 'pwd': 'e10adc3949ba59abbe56e057f20f883e', 'key': '505'}}, 'name': 'login', 'validate': [{'comparator': 'equals', 'check': 'status', 'expected': '200'}], 'extract': [{'token': 'content.data.data.token'}]}}
2019-06-13 10:27:56,650 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- login用例更新成功: {'test': {'request': {'url': 'http://apicommontest.hongyantu.com/commonapi/', 'method': 'POST', 'data': {'action': 'Indexs.LoginByPwd', 'time': '0', 'phone': '17706120671', 'pwd': 'e10adc3949ba59abbe56e057f20f883e', 'key': '505'}}, 'name': 'login', 'validate': [{'comparator': 'equals', 'check': 'status', 'expected': 200}], 'extract': [{'token': 'content.data.data.token'}]}}
2019-06-13 10:30:10,397 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- login用例更新成功: {'test': {'request': {'url': 'http://apicommontest.hongyantu.com/commonapi/', 'method': 'POST', 'data': {'action': 'Indexs.LoginByPwd', 'time': '0', 'phone': '17706120671', 'pwd': 'e10adc3949ba59abbe56e057f20f883e', 'key': '505'}}, 'name': 'login', 'validate': [{'comparator': 'equals', 'check': 'status_code', 'expected': 200}], 'extract': [{'token': 'content.data.data.token'}]}}
2019-06-13 10:37:36,713 [HttpRunnerManager:192] [operation:add_config_data] [INFO]- tokentest配置添加成功: {'config': {'request': {}, 'name': 'tokentest'}}
2019-06-13 10:46:50,778 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-06-13 10:47:13,468 [HttpRunnerManager:55] [views:login] [INFO]- alita 登录成功
2019-06-13 16:02:27,977 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-06-13 16:02:37,230 [HttpRunnerManager:54] [views:login] [INFO]- alita 登录成功
2019-06-13 16:05:58,166 [HttpRunnerManager:163] [operation:add_case_data] [INFO]- login用例更新成功: {'test': {'request': {'url': '/commonapi/', 'method': 'POST', 'data': {'action': 'Indexs.LoginByPwd', 'time': '0', 'phone': '17706120671', 'pwd': 'e10adc3949ba59abbe56e057f20f883e', 'key': '505'}}, 'name': 'login', 'validate': [{'comparator': 'equals', 'check': 'status_code', 'expected': 200}], 'extract': [{'token': 'content.data.data.token'}]}}
2019-06-14 13:19:06,140 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-06-14 13:19:17,364 [HttpRunnerManager:54] [views:login] [INFO]- alita 登录成功
2019-06-14 13:19:21,480 [HttpRunnerManager:54] [views:login] [INFO]- alita 登录成功
2019-07-17 17:35:48,477 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-07-17 17:35:58,178 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-07-17 17:36:02,650 [django.request:93] [base:get_response] [WARNING]- Not Found: /login
2019-07-17 17:36:26,531 [HttpRunnerManager:54] [views:login] [INFO]- alita 登录成功
2019-07-17 17:45:09,874 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-07-17 17:45:54,005 [HttpRunnerManager:59] [views:login] [INFO]- alita 登录失败, 请检查用户名或者密码
2019-07-17 17:46:31,873 [HttpRunnerManager:88] [views:log_out] [INFO]- alita退出
2019-07-17 17:57:09,442 [HttpRunnerManager:59] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-07-17 17:57:14,343 [HttpRunnerManager:59] [views:login] [INFO]- admin 登录失败, 请检查用户名或者密码
2019-08-29 15:10:18,104 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-08-29 15:10:26,493 [django.request:93] [base:get_response] [WARNING]- Not Found: /login
2019-08-29 15:10:33,191 [django.request:93] [base:get_response] [WARNING]- Not Found: /login/
2019-08-29 15:12:45,749 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-08-29 15:12:50,442 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-08-29 15:12:57,211 [django.request:93] [base:get_response] [WARNING]- Not Found: /cases
2019-08-29 15:15:44,811 [django.request:93] [base:get_response] [WARNING]- Not Found: /get_project_info
2019-08-29 15:23:15,281 [HttpRunnerManager:54] [views:login] [INFO]- alita 登录成功
2019-08-29 15:25:34,962 [HttpRunnerManager:54] [views:login] [INFO]- alita 登录成功
2019-08-29 15:27:26,129 [HttpRunnerManager:54] [views:login] [INFO]- alita 登录成功
2019-11-15 13:21:38,657 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-11-15 13:23:04,283 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-11-15 13:23:06,274 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2019-11-15 13:23:10,862 [django.request:93] [base:get_response] [WARNING]- Not Found: /
